version: 2

models:
    - name: fct_orders
      tests: 
        - dbt_expectations.expect_table_row_count_to_be_between:
           min_value: 1000

    - name: dim_customers
      
      columns:
       - name: avg_order_value
         tests:
          - dbt_expectations.expect_column_mean_to_be_between:
              min_value: 0
              max_value: 100000